import { TFunction } from "i18next"

export const getProjects = (t: TFunction) => [
  {
    title: t("projectsPage.project.miniBouncer.title"),
    description: t("projectsPage.project.miniBouncer.description"),
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Framer Motion",
      "Cloudflare",
      "EmailJS",
    ],
    clipSrc: "/movies/mini-bouncer.mp4",
    previewSrc: "/images/mini-bouncer.png",
    link: "https://mini-bouncer.com",
  },
  {
    title: t("projectsPage.project.dukeFlooring.title"),
    description: t("projectsPage.project.dukeFlooring.description"),
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Framer Motion",
      "Swiper",
    ],
    clipSrc: "/movies/dukeflooring.mp4",
    previewSrc: "/images/duke.jpg",
    link: "https://dukeflooring.com/",
  },
  {
    title: t("projectsPage.project.Haruoto.title"),
    description: t("projectsPage.project.Haruoto.description"),
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Framer Motion",
      "Chart.js",
      "Axios",
      "React Router",
      "Node.js",
      "Express",
      "Prisma",
      "JWT",
    ],
    clipSrc: "/movies/haruoto.mp4",
    previewSrc: "/images/haruoto.jpg",
    link: "https://haruoto.pages.dev/",
  },
  {
    title: t("projectsPage.project.modular.title"),
    description: t("projectsPage.project.modular.description"),
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Framer Motion",
    ],
    clipSrc: "/movies/modular.mp4",
    previewSrc: "/images/modular.jpg",
    link: "https://modular-home.pages.dev/",
  },
  {
    title: t("projectsPage.project.przysnilo.title"),
    description: t("projectsPage.project.przysnilo.description"),
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Axios",
      "React Router",
      "Node.js",
      "Express",
      "Prisma",
      "JWT",
    ],
    clipSrc: "/movies/przysnilo.mp4",
    previewSrc: "/images/przysnilo.jpg",
  },
]
